### ISSUE TITLE
Please consider this

### ISSUE THREAD

**Issue by minerva1993** [kadryjh1724/gang_generator#6]
poo
💩

**Comment by minerva1993** [comment]
💩
💩💩
💩💩💩
💩💩💩💩
💩💩💩💩💩

**Comment by youngwan-kim** [comment]
저녁 메뉴 추천좀

**Comment by minerva1993** [comment]
> 저녁 메뉴 추천좀
💩

**Comment by youngwan-kim** [comment]
너나먹어

**Comment by youngwan-kim** [comment]
@youngwan-kim 형님.한테 말 하는 버릇이. 그게 뭐야?

**Comment by minerva1993** [comment]
> 너나먹어

박사한테 못허는 말이 없구.

**Comment by kadryjh1724** [comment]
백날 응가하기 (42/100)

**Comment by youngwan-kim** [comment]
![lebronsunshinecover](https://github.com/kadryjh1724/gang_generator/assets/68631419/a80b796a-4704-4930-ac78-5c5c21d38f48)

**Comment by kadryjh1724** [comment]
lebronbon jenkić
